insert into times(teamName) values('ABC');
insert into times(teamName) values('ALECRIM');
insert into times(teamName) values('AMÉRICA-MG');
insert into times(teamName) values('AMERICANO');
insert into times(teamName) values('AMÉRICA-RJ');
insert into times(teamName) values('AMÉRICA-RN');
insert into times(teamName) values('AMÉRICA-SP');
insert into times(teamName) values('ANAPOLINA');
insert into times(teamName) values('ASA');
insert into times(teamName) values('ATLÉTICO-GO');
insert into times(teamName) values('ATLÉTICO-MG');
insert into times(teamName) values('ATLÉTICO-PR');
insert into times(teamName) values('AUTO ESPORTE');
insert into times(teamName) values('AVAÍ');
insert into times(teamName) values('BAHIA');
insert into times(teamName) values('BANGU');
insert into times(teamName) values('BARUERI');
insert into times(teamName) values('BOTAFOGO');
insert into times(teamName) values('BOTAFOGO-PB');
insert into times(teamName) values('BOTAFOGO-SP');
insert into times(teamName) values('BRAGANTINO');
insert into times(teamName) values('BRASIL');
insert into times(teamName) values('BRASÍLIA');
insert into times(teamName) values('BRASILIENSE');
insert into times(teamName) values('CALDENSE');
insert into times(teamName) values('CAMPINENSE');
insert into times(teamName) values('CAMPO GRANDE');
insert into times(teamName) values('CATUENSE');
insert into times(teamName) values('CAXIAS');
insert into times(teamName) values('CEARÁ');
insert into times(teamName) values('CENTRAL');
insert into times(teamName) values('CEUB');
insert into times(teamName) values('CHAPECOENSE');
insert into times(teamName) values('COLATINA');
insert into times(teamName) values('COLORADO');
insert into times(teamName) values('COMERCIAL-MS');
insert into times(teamName) values('COMERCIAL-SP');
insert into times(teamName) values('CONFIANÇA');
insert into times(teamName) values('CORINTHIANS');
insert into times(teamName) values('CORITIBA');
insert into times(teamName) values('CORUMBAENSE');
insert into times(teamName) values('CRB');
insert into times(teamName) values('CRICIÚMA');
insert into times(teamName) values('CRUZEIRO');
insert into times(teamName) values('CSA');
insert into times(teamName) values('DESPORTIVA');
insert into times(teamName) values('DOM BOSCO');
insert into times(teamName) values('FAST');
insert into times(teamName) values('FERROVIÁRIA');
insert into times(teamName) values('FERROVIÁRIO');
insert into times(teamName) values('FIGUEIRENSE');
insert into times(teamName) values('FLAMENGO');
insert into times(teamName) values('FLAMENGO-PI');
insert into times(teamName) values('FLUMINENSE');
insert into times(teamName) values('FLUMINENSE-BA');
insert into times(teamName) values('FORTALEZA');
insert into times(teamName) values('FRANCANA');
insert into times(teamName) values('GALÍCIA');
insert into times(teamName) values('GAMA');
insert into times(teamName) values('GOIÂNIA');
insert into times(teamName) values('GOIÁS');
insert into times(teamName) values('GOYTACAZ');
insert into times(teamName) values('GRÊMIO');
insert into times(teamName) values('GRÊMIO MARINGÁ');
insert into times(teamName) values('GRÊMIO PRUDENTE');
insert into times(teamName) values('GUARÁ');
insert into times(teamName) values('GUARANI');
insert into times(teamName) values('INTERNACIONAL');
insert into times(teamName) values('INTERNACIONAL-SM');
insert into times(teamName) values('INTERNACIONAL-SP');
insert into times(teamName) values('IPATINGA');
insert into times(teamName) values('ITABAIANA');
insert into times(teamName) values('ITABUNA');
insert into times(teamName) values('ITUMBIARA');
insert into times(teamName) values('JOINVILLE');
insert into times(teamName) values('JUVENTUDE');
insert into times(teamName) values('JUVENTUS');
insert into times(teamName) values('LEÔNICO');
insert into times(teamName) values('LONDRINA');
insert into times(teamName) values('MALUTROM');
insert into times(teamName) values('MARANHÃO');
insert into times(teamName) values('MARINGÁ');
insert into times(teamName) values('MIXTO');
insert into times(teamName) values('MOTO CLUB');
insert into times(teamName) values('NACIONAL');
insert into times(teamName) values('NÁUTICO');
insert into times(teamName) values('NOROESTE');
insert into times(teamName) values('NOVO HAMBURGO');
insert into times(teamName) values('OLARIA');
insert into times(teamName) values('OPERÁRIO-MS');
insert into times(teamName) values('OPERÁRIO-MT');
insert into times(teamName) values('OPERÁRIO-PR');
insert into times(teamName) values('PALMEIRAS');
insert into times(teamName) values('PARANÁ');
insert into times(teamName) values('PAYSANDU');
insert into times(teamName) values('PIAUÍ');
insert into times(teamName) values('PINHEIROS');
insert into times(teamName) values('PONTE PRETA');
insert into times(teamName) values('PORTUGUESA');
insert into times(teamName) values('POTIGUAR');
insert into times(teamName) values('REMO');
insert into times(teamName) values('RIO BRANCO');
insert into times(teamName) values('RIO NEGRO');
insert into times(teamName) values('RIVER');
insert into times(teamName) values('SAMPAIO CORRÊA');
insert into times(teamName) values('SANTA CRUZ');
insert into times(teamName) values('SANTO ANDRÉ');
insert into times(teamName) values('SANTOS');
insert into times(teamName) values('SÃO BENTO');
insert into times(teamName) values('SÃO CAETANO');
insert into times(teamName) values('SÃO JOSÉ');
insert into times(teamName) values('SÃO PAULO');
insert into times(teamName) values('SÃO PAULO-RS');
insert into times(teamName) values('SERGIPE');
insert into times(teamName) values('SOBRADINHO');
insert into times(teamName) values('SPORT');
insert into times(teamName) values('TAGUATINGA');
insert into times(teamName) values('TIRADENTES');
insert into times(teamName) values('TREZE');
insert into times(teamName) values('TUNA LUSO');
insert into times(teamName) values('UBERABA');
insert into times(teamName) values('UBERLÂNDIA');
insert into times(teamName) values('UNIÃO SÃO JOÃO');
insert into times(teamName) values('VASCO');
insert into times(teamName) values('VILA NOVA-GO');
insert into times(teamName) values('VILLA NOVA-MG');
insert into times(teamName) values('VITÓRIA-BA');
insert into times(teamName) values('VITÓRIA-ES');
insert into times(teamName) values('VOLTA REDONDA');
insert into times(teamName) values('XV DE JAÚ');
insert into times(teamName) values('XV DE PIRACICABA');
